const phrases = [
  'comanchero',
  'berber fil',
  'eski sevgili',
  'akdeniz foku',
  'john locke',
  'millennium fuck',
  'piyes',
  'çaylak',
  'birinci nesil hayvan',
  'muz kabuğu',
  'headbanger',
  'liseli ceren',
  'ajdar anık',
  'oregon valisi',
  'california valisi',
  'hayalet avcısı',
  'duman avcısı',
  'george costanza',
  'cosmo kramer',
  'hobbit',
  'gondor vekilharcı',
  'kardanadam',
  'klingon gemisi komutanı',
  'victor garber',
  'ron rifkin',
  'julian sark',
  'blythe doll',
  'tony almeida',
  'katee sackhoff',
  'bob kelso',
  'marissa cooper',
  'hiro nakamura',
  'claire bennett',
  'kim bauer',
  'mia kirshner',
  'david hewlett',
  'dan shea',
  'mary-louise parker',
  'ray romano',
  'will tippin',
  'tobias fünke',
  'george oscar bluth',
  'oğlak burcu',
  'boğa burcu',
  'laptop pili',
  'a drinking song',
  'daniel amokachi',
  'arzuhalci',
  'squidward tentacles',
  'tamagotchi',
  'bean burger',
  'clarence seedorf',
  'plastik ördek',
  'ornitorenk',
  'babazula',
  'art vandaley',
  'dewey',
  'reese',
  'malcolm',
  'atlıkarınca',
  'fazla bileti olan var mı? diye soran adamlar',
  'punk',
  'emmoğlu',
  'çeribaşı',
  'falçatalı travesti',
  'greenpeace üyesi',
  'marlboro paketi',
  'kanun hükmünde kararname',
  'bağkur emeklisi',
  'kurbanlık koyun',
  'veresiyeci',
  'kayserili işadamı',
  'art direktör',
  'haza beyefendi',
  'haza hanımefendi',
  'donut',
  'intellimouse',
  'wii',
  'akmar müdavimi',
  'ortam çocuğu',
  'turuncu kulaklıklı walkman',
  'ipod',
  'tatil kasabası bilekliği',
  'anders frisk',
  'paratrooper',
  'batık banka mudii',
  'halısaha kalecisi',
  'rus turist',
  'haçlı ordusu',
  'bahtsız bedevi',
  'uche okechukwu',
  'mr.eko',
  'rafael van der vaart',
  'tiki',
  'melanie pain',
  'beyaz çorap giyenler',
  'petek dinçöz',
  'karıncayiyen',
  'real doll',
  'pili biten vibratör',
  'nokia şarjı',
  "photoshop layer'ı",
  'gisele bündchen',
  'kristel kama',
  'kombine biletli taraftar',
  'taklit ülker ürünü',
  'lolipop',
  'birden fazla doğumgünü hediyesi',
  'ikiden fazla uyku düzeni',
  'isviçreli futbolcu',
  'kardak sakini',
  'yunan başkonsolosu',
  'avrupa birliği üye ülke vatandaşı',
  'vize görevlisi',
  'lauren graham',
  'zekeriya beyaz',
  'retina',
  'hayırsız evlat',
  'gibi gibi',
  'emmanuel amunike',
  'rashidi yekini',
  'jorge campos',
  'hakan mild',
  'ciriaco sforza',
  'stephane chapuisat',
  'alain sutter',
  '%50',
  'krassimir balakov',
  'florin raducioiu',
  'ulf kirsten',
  'josé emilio amavisca',
  'laudrup kardeşler',
  'yuri nikiforov',
  'daniele massaro',
  'viktor onopko',
  'sean dundee',
  'trifon ivanov',
  'bot',
];

const getRandomPhrase = () => {
  const randomIndex = Math.floor(Math.random() * phrases.length);
  document.getElementById('z').textContent = phrases[randomIndex];
};

document.addEventListener('DOMContentLoaded', getRandomPhrase);
